# bwtest — Bandwidth Console (Java/Maven) + bwagent (Rust/Cargo)
#
# This Makefile does not replace either build system. Maven owns the Java build
# and Cargo owns the Rust build; make coordinates them, adds the GNU standard
# target suite, and drives jpackage/nfpm for the installers.
#
#   ./configure && make && make check && sudo make install
#
# Run 'make help' for the full target list.

# Overridable so a containerised build can configure itself without clobbering
# the config.mk belonging to the developer whose repo is bind-mounted in.
CONFIG_MK ?= config.mk
# -include, not include: a missing config.mk is diagnosed by the guard below.
# Plain include makes GNU make print its own "No such file or directory" first,
# which buries the instruction that actually helps.
-include $(CONFIG_MK)

# config.mk is generated by ./configure. Without it every path below is empty,
# so fail with an instruction rather than doing something surprising.
ifeq ($(wildcard $(CONFIG_MK)),)
$(error Run ./configure first)
endif

SHELL       = /bin/sh
top_srcdir := $(CURDIR)

CONSOLE_DIR = $(top_srcdir)/console
AGENT_DIR   = $(top_srcdir)/agent
PKG_DIR     = $(top_srcdir)/packaging
RES_DIR     = $(PKG_DIR)/resources
BUILD_DIR   = $(top_srcdir)/build
DIST_DIR    = $(PKG_DIR)/dist

INSTALL         = install
INSTALL_PROGRAM = $(INSTALL) -m 755
INSTALL_DATA    = $(INSTALL) -m 644

APP_NAME    = Bandwidth Console
APP_VENDOR  = bwtest
APP_DESC    = Control plane and report nexus for bandwidth testing
MAIN_CLASS  = com.bwtest.console.Launcher
CONSOLE_JAR = $(CONSOLE_DIR)/target/bwconsole-$(VERSION).jar

# Modules jdeps cannot see because nothing names them: Unsafe, the EC provider
# that TLS needs at handshake time, and locale data. See app-image below.
INVISIBLE_MODULES = jdk.unsupported,jdk.crypto.ec,jdk.localedata
JAVAFX_MODULES    = javafx.controls,javafx.graphics

MVNFLAGS  ?= -B
CARGOFLAGS ?=

ifeq ($(HOST_ARCH),arm64)
  RUST_TRIPLE = aarch64-unknown-linux-gnu
  DEB_ARCH    = arm64
  RPM_ARCH    = aarch64
else
  RUST_TRIPLE = x86_64-unknown-linux-gnu
  DEB_ARCH    = amd64
  RPM_ARCH    = x86_64
endif

# jpackage rejects an icon in the wrong format for the platform and silently
# falls back to the generic Java icon, so pick per host.
ICON = $(RES_DIR)/bwconsole.png
ifeq ($(HOST_OS),macos)
  ICON = $(RES_DIR)/bwconsole.icns
endif
ifeq ($(HOST_OS),windows)
  ICON = $(RES_DIR)/bwconsole.ico
endif

# macOS bundles carry CFBundleVersion, whose first component must be >= 1, so a
# 0.x project version cannot be used verbatim — jpackage refuses outright.
# There is no mac-specific version flag, so override this to give macOS
# artifacts their own version while Linux keeps the project's:
#
#   make dmg MACOS_APP_VERSION=1.0.0
#
# Linux and Windows are unaffected and use VERSION as-is.
MACOS_APP_VERSION ?= $(VERSION)
APP_VERSION = $(VERSION)
ifeq ($(HOST_OS),macos)
  APP_VERSION = $(MACOS_APP_VERSION)
endif

# cargo-zigbuild pins the agent's glibc floor so it runs on distros older than
# the build host; without it we fall back to a native build and say so.
ifeq ($(HAVE_ZIGBUILD),yes)
  AGENT_BIN   = $(AGENT_DIR)/target/$(RUST_TRIPLE)/release/bwagent
  AGENT_BUILD = $(CARGO) zigbuild --release --target $(RUST_TRIPLE).$(GLIBC_FLOOR) $(CARGOFLAGS)
else
  AGENT_BIN   = $(AGENT_DIR)/target/release/bwagent
  AGENT_BUILD = $(CARGO) build --release $(CARGOFLAGS)
endif

.PHONY: all console agent check test installdirs install uninstall \
        installcheck clean mostlyclean distclean maintainer-clean \
        dist distcheck app-image deb rpm packages verify icons help TAGS

# ------------------------------------------------------------------- build --
all:
ifeq ($(BUILD_CONSOLE),yes)
	@$(MAKE) console
endif
ifeq ($(BUILD_AGENT),yes)
	@$(MAKE) agent
endif
	@echo "built $(PACKAGE) $(VERSION)"

console: $(CONSOLE_JAR)

# Maven decides when to recompile; the phony-ish dependency on the sources
# keeps make from skipping it when a source is newer than the jar.
$(CONSOLE_JAR): $(shell find $(CONSOLE_DIR)/src -type f 2>/dev/null) $(CONSOLE_DIR)/pom.xml
	@echo "  MVN      package"
	@cd $(CONSOLE_DIR) && $(MVN) $(MVNFLAGS) -q package -DskipTests

agent:
	@echo "  CARGO    build --release"
	@cd $(AGENT_DIR) && $(AGENT_BUILD)
	@$(MAKE) -s check-glibc-floor

# Fails the build if the agent needs a newer glibc than configured. Cheap, and
# it catches a silent fallback to a native build before a package ships.
#
# This deliberately runs whether or not cargo-zigbuild is present. It used to be
# gated behind HAVE_ZIGBUILD=yes, which inverted its purpose: the check was
# skipped in exactly the case that produces an over-linked binary. Building on
# a modern host without zigbuild silently yielded an agent needing GLIBC_2.39,
# and nothing said so until it failed to start on debian 12 and rocky 9 — after
# packaging, in a container, with no error text.
#
# Set ALLOW_HOST_GLIBC=1 to build against the host glibc on purpose (a local
# dev build you have no intention of packaging).
.PHONY: check-glibc-floor
check-glibc-floor:
	@if command -v objdump >/dev/null 2>&1; then \
	  max=$$(objdump -T $(AGENT_BIN) 2>/dev/null | grep -o 'GLIBC_[0-9.]*' | sort -uV | tail -1); \
	  if [ -n "$$max" ]; then \
	    if [ "$$(printf '%s\nGLIBC_$(GLIBC_FLOOR)\n' $$max | sort -V | tail -1)" != "GLIBC_$(GLIBC_FLOOR)" ]; then \
	      if [ -n "$(ALLOW_HOST_GLIBC)" ]; then \
	        echo "  WARN     agent requires $$max, above the GLIBC_$(GLIBC_FLOOR) floor (ALLOW_HOST_GLIBC set)"; \
	      else \
	        echo "$(AGENT_BIN): requires $$max, above the GLIBC_$(GLIBC_FLOOR) floor." >&2; \
	        echo "This binary will not start on distros older than the build host." >&2; \
	        echo "  install cargo-zigbuild + zig, then re-run ./configure   (pins the floor)" >&2; \
	        echo "  or lower the floor:   ./configure --with-glibc-floor=$${max#GLIBC_}" >&2; \
	        echo "  or accept host glibc: make agent ALLOW_HOST_GLIBC=1" >&2; \
	        exit 1; \
	      fi; \
	    else \
	      echo "  CHECK    agent requires at most $$max"; \
	    fi; \
	  fi; \
	fi

# -------------------------------------------------------------------- test --
check test:
ifeq ($(BUILD_AGENT),yes)
	@echo "  CARGO    test"
	@cd $(AGENT_DIR) && $(CARGO) test --release
endif
ifeq ($(BUILD_CONSOLE),yes)
	@echo "  MVN      test"
	@cd $(CONSOLE_DIR) && $(MVN) $(MVNFLAGS) -q test
endif

# ----------------------------------------------------------------- install --
# A jpackage app-image: the app, its jars, and a jlinked JDK+JavaFX runtime.
# This is what makes the install self-contained — no system Java is consulted
# at any point, and none is required on the target machine.
#
# The layout is not the same across platforms. macOS produces a .app bundle
# with everything under Contents/; elsewhere it is a plain directory with
# bin/ and lib/. Both are described here so the install rules stay generic.
APP_IMAGE     = $(BUILD_DIR)/app-image/$(APP_NAME)
APP_INSTDIR   = bwconsole
APP_LAUNCHER  = bin/$(APP_NAME)
APP_RELEASE   = lib/runtime/release
ifeq ($(HOST_OS),macos)
  APP_IMAGE    = $(BUILD_DIR)/app-image/$(APP_NAME).app
  APP_INSTDIR  = bwconsole.app
  APP_LAUNCHER = Contents/MacOS/$(APP_NAME)
  APP_RELEASE  = Contents/runtime/Contents/Home/release
endif

.PHONY: check-app-version
check-app-version:
	@case '$(HOST_OS):$(APP_VERSION)' in \
	  macos:0*) \
	    echo "macOS cannot package version $(APP_VERSION): CFBundleVersion's first" >&2; \
	    echo "component must be >= 1, and jpackage has no mac-specific version flag." >&2; \
	    echo "Either bump <version> in console/pom.xml, or build with an override:" >&2; \
	    echo "    make $(or $(MAKECMDGOALS),app-image) MACOS_APP_VERSION=1.0.0" >&2; \
	    exit 1 ;; \
	esac

# configure records an absolute path to the jmods, and that path can stop being
# valid between configure and build — a scratch or /tmp location is reaped, an
# external volume is unmounted. Testing only "is the variable set" let a
# vanished directory sail past this guard and fail deep inside jdeps with an
# opaque module error. Check it is still there, and still jmods.
.PHONY: check-jmods
check-jmods:
	@if [ -z "$(JAVAFX_JMODS)" ]; then \
	  echo "JAVAFX_JMODS is not set — re-run ./configure --with-javafx-jmods=DIR" >&2; \
	  exit 1; fi
	@if [ ! -d "$(JAVAFX_JMODS)" ]; then \
	  echo "JAVAFX_JMODS points at a directory that no longer exists:" >&2; \
	  echo "    $(JAVAFX_JMODS)" >&2; \
	  echo "Re-run ./configure --with-javafx-jmods=DIR pointing at a durable path" >&2; \
	  echo "(not a temp or scratch directory)." >&2; \
	  exit 1; fi
	@if ! ls "$(JAVAFX_JMODS)"/*.jmod >/dev/null 2>&1; then \
	  echo "$(JAVAFX_JMODS) contains no .jmod files." >&2; \
	  echo "That is most likely the JavaFX SDK; jpackage needs the *jmods*" >&2; \
	  echo "bundle instead — download it from https://openjfx.io" >&2; \
	  exit 1; fi

app-image: check-app-version check-jmods $(CONSOLE_JAR)
	@echo "  JDEPS    computing module set"
	@rm -rf $(BUILD_DIR)/app-image $(BUILD_DIR)/input
	@mkdir -p $(BUILD_DIR)/input
	@cp $(CONSOLE_JAR) $(BUILD_DIR)/input/
	@if [ -f "$(AGENT_BIN)" ]; then cp $(AGENT_BIN) $(BUILD_DIR)/input/; \
	 else echo "  WARN     no agent binary — installer will not bundle one"; fi
	@mods=$$($(JDEPS) --multi-release 21 --ignore-missing-deps --print-module-deps \
	          --module-path $(JAVAFX_JMODS) $(CONSOLE_JAR)); \
	 echo "  JPACKAGE app-image [$$mods,$(JAVAFX_MODULES),$(INVISIBLE_MODULES)]"; \
	 $(JPACKAGE) --type app-image \
	   --name "$(APP_NAME)" --app-version "$(APP_VERSION)" --vendor "$(APP_VENDOR)" \
	   --description "$(APP_DESC)" \
	   --input $(BUILD_DIR)/input --main-jar $(notdir $(CONSOLE_JAR)) \
	   --main-class $(MAIN_CLASS) \
	   --module-path $(JAVAFX_JMODS) \
	   --add-modules "$$mods,$(JAVAFX_MODULES),$(INVISIBLE_MODULES)" \
	   --java-options -Dprism.lcdtext=false \
	   --icon $(ICON) \
	   --dest $(BUILD_DIR)/app-image

installdirs:
	@mkdir -p $(DESTDIR)$(bindir) $(DESTDIR)$(libdir) \
	          $(DESTDIR)$(datadir)/applications \
	          $(DESTDIR)$(datadir)/icons/hicolor/256x256/apps \
	          $(DESTDIR)$(datadir)/doc/$(PACKAGE)

install: all installdirs
ifeq ($(BUILD_CONSOLE),yes)
	@$(MAKE) app-image
	@echo "  INSTALL  $(DESTDIR)$(libdir)/$(APP_INSTDIR)"
	@rm -rf "$(DESTDIR)$(libdir)/$(APP_INSTDIR)"
	@mkdir -p "$(DESTDIR)$(libdir)/$(APP_INSTDIR)"
	@cp -R "$(APP_IMAGE)/." "$(DESTDIR)$(libdir)/$(APP_INSTDIR)/"
	@printf '#!/bin/sh\nexec "%s/%s/%s" "$$@"\n' \
	    '$(libdir)' '$(APP_INSTDIR)' '$(APP_LAUNCHER)' > $(DESTDIR)$(bindir)/bwconsole
	@chmod 755 $(DESTDIR)$(bindir)/bwconsole
	@echo "  INSTALL  $(DESTDIR)$(bindir)/bwconsole"
# Desktop entries and hicolor icons are freedesktop conventions; macOS gets its
# menu presence from the .app bundle's own Info.plist instead.
ifneq ($(HOST_OS),macos)
	@$(INSTALL_DATA) $(RES_DIR)/bwconsole.png \
	    $(DESTDIR)$(datadir)/icons/hicolor/256x256/apps/bwconsole.png
	@printf '[Desktop Entry]\nType=Application\nName=%s\nComment=%s\nExec=%s/bwconsole\nIcon=bwconsole\nCategories=Network;\nTerminal=false\n' \
	    '$(APP_NAME)' '$(APP_DESC)' '$(bindir)' \
	    > $(DESTDIR)$(datadir)/applications/bwconsole.desktop
endif
endif
ifeq ($(BUILD_AGENT),yes)
	@echo "  INSTALL  $(DESTDIR)$(bindir)/bwagent"
	@$(INSTALL_PROGRAM) $(AGENT_BIN) $(DESTDIR)$(bindir)/bwagent
	@mkdir -p $(DESTDIR)$(sysconfdir)/bwagent
	@if [ ! -f $(DESTDIR)$(sysconfdir)/bwagent/bwagent.env ]; then \
	   $(INSTALL_DATA) $(PKG_DIR)/systemd/bwagent.env \
	       $(DESTDIR)$(sysconfdir)/bwagent/bwagent.env; \
	 else echo "  KEEP     $(sysconfdir)/bwagent/bwagent.env (existing config)"; fi
	@mkdir -p $(DESTDIR)$(systemdunitdir)
	@$(INSTALL_DATA) $(PKG_DIR)/systemd/bwagent.service \
	    $(DESTDIR)$(systemdunitdir)/bwagent.service
endif
	@$(INSTALL_DATA) $(top_srcdir)/LICENSE $(DESTDIR)$(datadir)/doc/$(PACKAGE)/LICENSE
	@echo "install complete."

uninstall:
	@echo "  REMOVE   $(DESTDIR)$(libdir)/$(APP_INSTDIR)"
	@rm -rf "$(DESTDIR)$(libdir)/$(APP_INSTDIR)"
	@rm -f  $(DESTDIR)$(bindir)/bwconsole $(DESTDIR)$(bindir)/bwagent
	@rm -f  $(DESTDIR)$(datadir)/applications/bwconsole.desktop
	@rm -f  $(DESTDIR)$(datadir)/icons/hicolor/256x256/apps/bwconsole.png
	@rm -f  $(DESTDIR)$(systemdunitdir)/bwagent.service
	@rm -rf $(DESTDIR)$(datadir)/doc/$(PACKAGE)
	@echo "  KEEP     $(sysconfdir)/bwagent (config preserved; remove by hand)"

# Checks an installed tree rather than a built one — the GNU meaning.
installcheck:
	@echo "  CHECK    $(DESTDIR)$(bindir)/bwagent"
	@$(DESTDIR)$(bindir)/bwagent --version
ifeq ($(BUILD_CONSOLE),yes)
	@echo "  CHECK    bundled runtime carries its own JVM"
	@test -f "$(DESTDIR)$(libdir)/$(APP_INSTDIR)/$(APP_RELEASE)" \
	  || { echo "no bundled runtime at $(APP_INSTDIR)/$(APP_RELEASE)" >&2; exit 1; }
	@grep -q 'java.net.http' "$(DESTDIR)$(libdir)/$(APP_INSTDIR)/$(APP_RELEASE)" \
	  || { echo "bundled runtime is missing java.net.http" >&2; exit 1; }
	@grep -q 'javafx.controls' "$(DESTDIR)$(libdir)/$(APP_INSTDIR)/$(APP_RELEASE)" \
	  || { echo "bundled runtime is missing javafx.controls" >&2; exit 1; }
	@test -x "$(DESTDIR)$(libdir)/$(APP_INSTDIR)/$(APP_LAUNCHER)" \
	  || { echo "launcher is missing or not executable" >&2; exit 1; }
	@echo "  OK       self-contained install (no system Java required)"
endif

# ---------------------------------------------------------------- packages --
# jpackage cannot cross-compile, so each format is produced on its own OS.
# On Linux these run natively; anywhere else they go through a container.
deb rpm: %:
ifeq ($(HOST_OS),linux)
	@$(MAKE) native-pkg PKG_TYPE=$@
else
	@$(MAKE) container-pkg PKG_TYPE=$@
endif

.PHONY: native-pkg container-pkg
native-pkg: check-jmods $(CONSOLE_JAR) agent
	@mkdir -p $(DIST_DIR) $(BUILD_DIR)/input
	@cp $(CONSOLE_JAR) $(BUILD_DIR)/input/
	@if [ -f "$(AGENT_BIN)" ]; then cp $(AGENT_BIN) $(BUILD_DIR)/input/; fi
	@case $(PKG_TYPE) in deb) gtk=libgtk-3-0 ;; rpm) gtk=gtk3 ;; esac; \
	 mods=$$($(JDEPS) --multi-release 21 --ignore-missing-deps --print-module-deps \
	          --module-path $(JAVAFX_JMODS) $(CONSOLE_JAR)); \
	 echo "  JPACKAGE --type $(PKG_TYPE)"; \
	 $(JPACKAGE) --type $(PKG_TYPE) \
	   --name "$(APP_NAME)" --app-version "$(APP_VERSION)" --vendor "$(APP_VENDOR)" \
	   --description "$(APP_DESC)" --license-file $(top_srcdir)/LICENSE \
	   --input $(BUILD_DIR)/input --main-jar $(notdir $(CONSOLE_JAR)) \
	   --main-class $(MAIN_CLASS) \
	   --module-path $(JAVAFX_JMODS) \
	   --add-modules "$$mods,$(JAVAFX_MODULES),$(INVISIBLE_MODULES)" \
	   --java-options -Dprism.lcdtext=false \
	   --icon $(ICON) \
	   --linux-shortcut --linux-menu-group Network \
	   --linux-package-name bwconsole --linux-app-category net \
	   --linux-package-deps "$$gtk" --linux-rpm-license-type MIT \
	   --dest $(DIST_DIR)
	@$(MAKE) agent-pkg PKG_TYPE=$(PKG_TYPE)

# nfpm expands nothing in contents.src, so the spec is a template we render.
.PHONY: agent-pkg
# Missing nfpm is a hard error, not a skip. This used to `exit 0`, so a native
# `make deb` on a host without nfpm reported success having built only the
# console package — the agent silently absent from a release. A build that
# cannot produce what was asked for must say so.
#
# Set ALLOW_MISSING_NFPM=1 to deliberately build console-only packages.
#
# One recipe line, deliberately: make runs each line in its own shell, so an
# `exit 0` in the skip branch would end only that line and the rest of the
# recipe would still run nfpm and fail. The whole body has to share the shell
# the early-exit happens in.
agent-pkg:
	@if ! command -v nfpm >/dev/null 2>&1; then \
	  if [ -n "$(ALLOW_MISSING_NFPM)" ]; then \
	    echo "  SKIP     agent $(PKG_TYPE) (nfpm not installed, ALLOW_MISSING_NFPM set)"; \
	    exit 0; \
	  fi; \
	  echo "nfpm is not installed, so no agent $(PKG_TYPE) can be built." >&2; \
	  echo "  install it:             https://nfpm.goreleaser.com" >&2; \
	  echo "  or build in a container: make $(PKG_TYPE) (from a non-Linux host)" >&2; \
	  echo "  or accept console-only:  make $(PKG_TYPE) ALLOW_MISSING_NFPM=1" >&2; \
	  exit 1; \
	fi; \
	set -e; \
	mkdir -p $(BUILD_DIR) $(DIST_DIR); \
	sed -e 's|$${AGENT_BIN}|$(AGENT_BIN)|g' \
	    -e 's|$${PKG_VERSION}|$(VERSION)|g' \
	    -e 's|$${PKG_ARCH}|$(DEB_ARCH)|g' \
	    -e 's|$${REPO_ROOT}|$(top_srcdir)|g' \
	    $(PKG_DIR)/nfpm/bwagent.yaml.in > $(BUILD_DIR)/bwagent.yaml; \
	echo "  NFPM     $(PKG_TYPE)"; \
	nfpm package --config $(BUILD_DIR)/bwagent.yaml --packager $(PKG_TYPE) --target $(DIST_DIR)

# Builds the Linux packages inside a container, so any host can produce them.
# The container re-enters this same Makefile — one definition of the build.
IMAGE ?= bwtest-build:$(HOST_ARCH)
container-pkg:
	@if [ -z "$(CONTAINER_ENGINE)" ]; then \
	  echo "no container engine — re-run ./configure --with-container-engine=podman" >&2; exit 1; fi
	@if [ "$(HOST_ARCH)" = "amd64" ] && [ "$$(uname -m)" != "x86_64" ]; then \
	  echo "Refusing to build amd64 packages on an arm64 host: rustc segfaults" >&2; \
	  echo "under qemu-user emulation. Use a native x86_64 host or CI." >&2; exit 1; fi
	@echo "  BUILD    $(IMAGE)"
	@$(CONTAINER_ENGINE) build --platform linux/$(HOST_ARCH) \
	    -f $(PKG_DIR)/docker/Dockerfile.linux -t $(IMAGE) $(top_srcdir)
	@echo "  RUN      make $(PKG_TYPE) in $(IMAGE)"
	@$(CONTAINER_ENGINE) run --rm --platform linux/$(HOST_ARCH) \
	    -v $(top_srcdir):/src -w /src $(IMAGE) \
	    sh -c 'CONFIG_MK=/tmp/config.mk ./configure --with-javafx-jmods=$$JAVAFX_JMODS >/dev/null && \
	           make CONFIG_MK=/tmp/config.mk $(PKG_TYPE)'

packages: deb rpm
	@ls -la $(DIST_DIR)

# Installs the built packages into clean containers of each distro family and
# checks they run — see packaging/verify-linux.sh for what is asserted.
verify:
	@$(PKG_DIR)/verify-linux.sh $(HOST_ARCH)

icons:
	@echo "  JAVA     GenerateIcon"
	@java $(RES_DIR)/GenerateIcon.java $(RES_DIR)
	@if command -v iconutil >/dev/null 2>&1; then \
	   rm -f $(RES_DIR)/bwconsole.icns; \
	   iconutil -c icns $(RES_DIR)/bwconsole.iconset -o $(RES_DIR)/bwconsole.icns; \
	   echo "  ICONUTIL bwconsole.icns"; \
	 else echo "  SKIP     .icns (iconutil is macOS-only)"; fi

# -------------------------------------------------------------------- dist --
distdir = $(PACKAGE)-$(VERSION)

# Packages the working tree, not HEAD. 'git archive HEAD' would silently ship
# the last commit — omitting uncommitted work and resurrecting deleted files —
# which is how you publish a tarball that cannot even be configured.
#
# 'git ls-files -co --exclude-standard' is exactly the right file set: tracked
# plus untracked, minus anything .gitignore excludes, so build output and
# packaging/dist stay out without a second exclude list to maintain.
dist:
	@echo "  DIST     $(distdir).tar.gz"
	@rm -rf $(BUILD_DIR)/$(distdir)
	@mkdir -p $(BUILD_DIR)/$(distdir)
	@if [ -d .git ] && command -v git >/dev/null 2>&1; then \
	   git ls-files -co --exclude-standard; \
	 else \
	   find . -type f -not -path './.git/*' -not -path './build/*' \
	          -not -path '*/target/*' -not -path './packaging/dist/*' \
	     | sed 's|^\./||'; \
	 fi > $(BUILD_DIR)/distfiles
	@tar cf - -T $(BUILD_DIR)/distfiles | tar xf - -C $(BUILD_DIR)/$(distdir)
	@tar czf $(distdir).tar.gz -C $(BUILD_DIR) $(distdir)
	@rm -rf $(BUILD_DIR)/$(distdir) $(BUILD_DIR)/distfiles

# Proves the tarball is self-sufficient: unpack it somewhere else, configure,
# build and test from scratch.
distcheck: dist
	@rm -rf $(BUILD_DIR)/distcheck
	@mkdir -p $(BUILD_DIR)/distcheck
	@tar xzf $(distdir).tar.gz -C $(BUILD_DIR)/distcheck
	@cd $(BUILD_DIR)/distcheck/$(distdir) && \
	   ./configure --prefix=$(BUILD_DIR)/distcheck/inst \
	       $(if $(JAVAFX_JMODS),--with-javafx-jmods=$(JAVAFX_JMODS)) >/dev/null && \
	   $(MAKE) all && $(MAKE) check && $(MAKE) install && $(MAKE) installcheck
	@echo "distcheck: $(distdir).tar.gz is ready for distribution"

# ------------------------------------------------------------------- clean --
mostlyclean:
	@rm -rf $(BUILD_DIR)

clean: mostlyclean
	@echo "  CLEAN    console, agent"
	@-cd $(CONSOLE_DIR) && $(MVN) $(MVNFLAGS) -q clean 2>/dev/null || rm -rf $(CONSOLE_DIR)/target
	@-cd $(AGENT_DIR) && $(CARGO) clean 2>/dev/null || rm -rf $(AGENT_DIR)/target
	@rm -rf $(DIST_DIR) $(PKG_DIR)/work

distclean: clean
	@rm -f config.mk $(distdir).tar.gz
	@rm -f $(CONSOLE_DIR)/dependency-reduced-pom.xml

maintainer-clean: distclean
	@echo "This command is intended for maintainers to use; it deletes files"
	@echo "that may require special tools to rebuild."
	@rm -f $(RES_DIR)/bwconsole.icns $(RES_DIR)/bwconsole.ico $(RES_DIR)/bwconsole.png
	@rm -rf $(RES_DIR)/bwconsole.iconset

TAGS:
	@if command -v ctags >/dev/null 2>&1; then \
	   ctags -R $(CONSOLE_DIR)/src $(AGENT_DIR)/src; echo "  CTAGS    tags"; \
	 else echo "  SKIP     ctags not installed"; fi

# -------------------------------------------------------------------- help --
help:
	@echo '$(PACKAGE) $(VERSION) — targets:'
	@echo ''
	@echo '  all              build console (Maven) and agent (Cargo)   [default]'
	@echo '  console          build the JavaFX console jar only'
	@echo '  agent            build the Rust agent only'
	@echo '  check | test     run cargo test and mvn test'
	@echo ''
	@echo '  app-image        jpackage app image: app + bundled JDK/JavaFX runtime'
	@echo '  install          install to $$(DESTDIR)$$(prefix)'
	@echo '  uninstall        remove an installed tree (keeps $$(sysconfdir))'
	@echo '  installcheck     verify an installed tree actually runs'
	@echo ''
	@echo '  deb / rpm        Linux packages (native on Linux, else container)'
	@echo '  packages         both of the above'
	@echo '  verify           install the packages into clean distro containers'
	@echo ''
	@echo '  dist             source tarball'
	@echo '  distcheck        unpack the tarball elsewhere and build it clean'
	@echo '  icons            regenerate the app icons'
	@echo ''
	@echo '  clean            remove build products'
	@echo '  distclean        also remove config.mk'
	@echo '  maintainer-clean also remove generated icons'
	@echo ''
	@echo 'Configured: $(HOST_OS)/$(HOST_ARCH), prefix $(prefix)'
